In [1]:
'''

Numpy 基本操作

'''
import numpy as np

In [2]:
# 製作陣列維陣列
arr1 = np.zeros(3, dtype=int)
arr2 = np.ones([2,3], dtype=float)
arr3 = np.empty([2,3])
arr4 = np.full([2,3,4], 111)
print('長度為3，所有值皆為0的整數陣列', arr1)
print('建立一個2X3，全部值皆為1的小數陣列', arr2)
print('建立一個2X3，無初始值陣列', arr3)
print('建立一個2X3X4，全部值皆為111的陣列',arr4)

長度為3，所有值皆為0的整數陣列 [0 0 0]
建立一個2X3，全部值皆為1的小數陣列 [[1. 1. 1.]
 [1. 1. 1.]]
建立一個2X3，無初始值陣列 [[2.e+000 2.e+000 2.e-323]
 [0.e+000 0.e+000 0.e+000]]
建立一個2X3X4，全部值皆為111的陣列 [[[111 111 111 111]
  [111 111 111 111]
  [111 111 111 111]]

 [[111 111 111 111]
  [111 111 111 111]
  [111 111 111 111]]]


In [3]:
# 陣列屬性
print('arr1維度', arr1.ndim)
print('arr2維度', arr2.ndim)
print('arr4維度', arr4.ndim)

print('arr1 Shape', arr1.shape)
print('arr2 Shape', arr2.shape)
print('arr4 Shape', arr4.shape)

print('arr1 Size', arr1.size)
print('arr2 Size', arr2.size)
print('arr4 Size', arr4.size)

arr1維度 1
arr2維度 2
arr4維度 3
arr1 Shape (3,)
arr2 Shape (2, 3)
arr4 Shape (2, 3, 4)
arr1 Size 3
arr2 Size 6
arr4 Size 24


In [4]:
# reshap陣列
arr4

array([[[111, 111, 111, 111],
        [111, 111, 111, 111],
        [111, 111, 111, 111]],

       [[111, 111, 111, 111],
        [111, 111, 111, 111],
        [111, 111, 111, 111]]])

In [5]:
arr4.reshape([2,12])

array([[111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111],
       [111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111]])

In [6]:
arr4.reshape([-1, 4])

array([[111, 111, 111, 111],
       [111, 111, 111, 111],
       [111, 111, 111, 111],
       [111, 111, 111, 111],
       [111, 111, 111, 111],
       [111, 111, 111, 111]])

In [7]:
arr4.reshape([1,1])

ValueError: cannot reshape array of size 24 into shape (1,1)